import { defineConfig, type Options } from "tsup";

/**
 * Dist build for `@apo/sdk`.
 *
 * Emits compiled ESM + .d.ts for the six published entry points so external
 * consumers can use the package under plain Node + plain tsc — no
 * --experimental-strip-types runtime, no allowImportingTsExtensions tsconfig
 * flag (both of which the monorepo's source style requires internally).
 *
 * Internal dev does NOT go through this build: the package.json `exports`
 * map has a `development` condition that routes the dashboard/cli/example-
 * service back to ./src/*.ts, so the live edit loop stays symlink-fast.
 *
 * The source uses .ts extensions in all relative imports (~84 sites); esbuild
 * (which tsup wraps) normalizes them in the emitted JS. No source rewrite
 * needed. Node builtins and the OpenTelemetry/effect runtime deps are marked
 * external so they resolve from the consumer's node_modules.
 */

const external = [
  // Runtime dependencies (from package.json "dependencies") — must resolve
  // from the consumer's node_modules, never bundled.
  "@opentelemetry/api",
  "@opentelemetry/context-async-hooks",
  "@opentelemetry/core",
  "@opentelemetry/exporter-trace-otlp-http",
  "@opentelemetry/resources",
  "@opentelemetry/sdk-trace-base",
  "@opentelemetry/semantic-conventions",
  "effect",
  // Node builtins used by the source (not in package.json).
  "fs",
  "fs/promises",
  "path",
  "url",
  "node:async_hooks",
];

const shared: Options = {
  format: ["esm"],
  platform: "node",
  target: "node20",
  sourcemap: true,
  clean: true,
  dts: true,
  external,
  splitting: true,
  banner: {
    js: [
      "// Auto-generated by `pnpm --filter @apo/sdk build` (tsup.config.ts).",
      "// Do not edit by hand — edit the src/ originals and rebuild.",
    ].join("\n"),
  },
};

export default defineConfig([
  {
    ...shared,
    entry: {
      index: "src/index.ts",
      "otel/index": "src/otel/index.ts",
      "agent-task/public": "src/agent-task/public.ts",
      "agent-task/integrations/ai-sdk": "src/agent-task/integrations/ai-sdk.ts",
      "agent-task/integrations/openai": "src/agent-task/integrations/openai.ts",
      "agent-task/integrations/anthropic": "src/agent-task/integrations/anthropic.ts",
    },
  },
]);
