from typing import Callable, TypeVar

_T = TypeVar("_T")

class _MarkDecorator:
    def __call__(self, *args: object, **kwargs: object) -> object: ...

class _MarkNamespace:
    def __getattr__(self, name: str) -> _MarkDecorator: ...

mark: _MarkNamespace

def fixture(*args: object, **kwargs: object) -> Callable[[Callable[..., _T]], Callable[..., _T]]: ...
def approx(expected: object, *args: object, **kwargs: object) -> object: ...
def main(args: object = ...) -> int: ...

class raises:
    value: object
    def __init__(self, expected_exception: object, *args: object, **kwargs: object) -> None: ...
    def __enter__(self) -> raises: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> bool | None: ...
