/**
 * Local span-durability sidecar: an upstream OpenTelemetry Collector
 * (otelcol-contrib, pinned) managed by the CLI.
 *
 * Why: task spans are only durable once the backend accepts them. A run
 * against a remote backend over a flaky network, or while the backend is
 * restarting, loses every span whose export retry window (seconds) expires —
 * silently. The collector sits on loopback, impersonates apo's ingest path
 * (`/api/public/otel/v1/traces`), and forwards through a bounded disk queue
 * that retries forever: the task process only has to reach localhost.
 *
 * Design contract (keep when editing):
 *   - The Authorization header reaches the collector via environment variable
 *     only — never written to the config file, never passed in argv.
 *   - The queue is a buffer, not a log: hard `max_size` cap, entries deleted
 *     on backend ack, drops (when full) counted by the collector's own
 *     `otelcol_exporter_enqueue_failed_spans` metric instead of filling disk.
 *   - Failures never block a run: callers fall back to direct export, which
 *     is exactly the pre-collector behavior.
 */

import { spawn, spawnSync, type ChildProcess } from "node:child_process";
import { createHash } from "node:crypto";
import { createWriteStream } from "node:fs";
import {
  closeSync,
  existsSync,
  mkdirSync,
  openSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { pipeline } from "node:stream/promises";

/** Pinned upstream release — validated config values below target this. */
export const COLLECTOR_VERSION = "0.160.0";

/** apo's canonical OTLP traces path; the receiver impersonates it. */
export const APO_TRACES_PATH = "/api/public/otel/v1/traces";

const DEFAULT_OTLP_PORT = 4318;
const DEFAULT_HEALTH_PORT = 13133;
const DEFAULT_MAX_QUEUE_BYTES = 512 * 1024 * 1024;
const DEFAULT_HEALTH_TIMEOUT_MS = 20_000;
const STOP_TIMEOUT_MS = 10_000;

export interface CollectorPaths {
  home: string;
  bin: string;
  config: string;
  log: string;
  queueDir: string;
}

export function collectorPaths(): CollectorPaths {
  const home = join(homedir(), ".apo", "collector");
  return {
    home,
    bin: join(home, "bin", "otelcol-contrib"),
    config: join(home, "config.yaml"),
    log: join(home, "collector.log"),
    queueDir: join(home, "queue"),
  };
}

export interface CollectorRenderOptions {
  /** Backend base URL, e.g. https://apo.example.com — spans are forwarded there. */
  backendUrl: string;
  otlpPort: number;
  healthPort: number;
  queueDir: string;
  maxQueueBytes: number;
}

/**
 * Render the collector YAML. Values are resolved from the caller's
 * environment decisions at render time; the only environment placeholder left
 * in the file is the auth header, so the secret never lands on disk.
 */
export function renderCollectorConfig(opts: CollectorRenderOptions): string {
  const exportUrl = `${opts.backendUrl.replace(/\/$/, "")}${APO_TRACES_PATH}`;
  return `# apo local span-durability sidecar — managed by the apo CLI.
#
# Receives OTLP/HTTP from apo task processes on localhost and forwards to the
# apo backend through a bounded, persistent (write-ahead-log) queue, so spans
# survive backend outages, flaky networks, and collector restarts without
# unbounded local growth. Entries are deleted as soon as the backend acks; in
# steady state the queue directory is nearly empty.
#
# Validated against otelcol-contrib ${COLLECTOR_VERSION}. Regenerated by the
# CLI on every start — manual edits are overwritten.

extensions:
  file_storage:
    directory: ${opts.queueDir}
    create_directory: true
    # Hard cap on disk. When reached, new batches are dropped and counted in
    # otelcol_exporter_enqueue_failed_spans instead of filling the disk.
    max_size: ${opts.maxQueueBytes}
    timeout: 1s
    compaction:
      on_start: true
      on_rebound: true
      directory: ${opts.queueDir}
  health_check:
    endpoint: 127.0.0.1:${opts.healthPort}

receivers:
  otlp:
    protocols:
      http:
        endpoint: 127.0.0.1:${opts.otlpPort}
        # Impersonate the apo ingest path so pointing a run at the collector
        # is one env var: AGENT_TASK_TRACE_ENDPOINT=http://127.0.0.1:<port>.
        traces_url_path: ${APO_TRACES_PATH}

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128
  batch:
    send_batch_size: 512
    send_batch_max_size: 1024
    timeout: 2s

exporters:
  otlphttp/apo:
    traces_endpoint: ${exportUrl}
    encoding: json
    # apo's ingest decompresses gzip with a bounded reader.
    compression: gzip
    headers:
      # Secret via environment only — never persisted to this file.
      Authorization: "\${env:APO_COLLECTOR_AUTH}"
    timeout: 30s
    sending_queue:
      enabled: true
      storage: file_storage
      # Batches kept while the backend is unreachable (also bounded by
      # file_storage max_size above).
      queue_size: 10000
      num_consumers: 4
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 60s
      # Never give up on a batch; the queue bounds are the only limit.
      max_elapsed_time: 0s

service:
  extensions: [file_storage, health_check]
  telemetry:
    logs:
      level: info
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/apo]
`;
}

/**
 * Decide whether the collector should run for a given backend. Auto-on only
 * where it pays (remote backends — localhost handoff to a local backend is
 * the same reliability class); APO_COLLECTOR=1/0 forces the decision either
 * way so it can be enabled in local tests and disabled on remote setups.
 */
export function decideCollectorEnabled(backendUrl: string): boolean {
  const forced = process.env.APO_COLLECTOR;
  if (forced !== undefined) {
    return forced === "1" || forced.toLowerCase() === "true";
  }
  try {
    return !isLoopbackHost(new URL(backendUrl));
  } catch {
    return false;
  }
}

function isLoopbackHost(url: URL): boolean {
  const host = url.hostname;
  return host === "localhost" || host === "127.0.0.1" || host === "::1" || host === "[::1]";
}

/** Map the current platform onto the upstream release asset naming. */
export function collectorPlatform(): { os: string; arch: string } | null {
  const os = process.platform === "darwin" ? "darwin" : process.platform === "linux" ? "linux" : null;
  const arch = process.arch === "x64" ? "amd64" : process.arch === "arm64" ? "arm64" : null;
  return os && arch ? { os, arch } : null;
}

export function collectorDownloadUrls(): { tarball: string; checksum: string } | null {
  const platform = collectorPlatform();
  if (!platform) return null;
  const base =
    `https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download` +
    `/v${COLLECTOR_VERSION}/otelcol-contrib_${COLLECTOR_VERSION}_${platform.os}_${platform.arch}`;
  return { tarball: `${base}.tar.gz`, checksum: `${base}.tar.gz.sha256` };
}

/**
 * Resolve the collector binary: an explicit override wins, then a previously
 * installed copy, then a checksum-verified one-time download. Returns null
 * when the platform has no upstream release (caller falls back to direct
 * export).
 */
export async function ensureCollectorBinary(
  onNotice?: (message: string) => void,
): Promise<string | null> {
  const override = process.env.APO_COLLECTOR_BIN;
  if (override) return override;

  const paths = collectorPaths();
  if (existsSync(paths.bin)) return paths.bin;

  const urls = collectorDownloadUrls();
  if (!urls) return null;

  onNotice?.(
    `Downloading otelcol-contrib v${COLLECTOR_VERSION} (one-time, ~95 MB)…`,
  );
  mkdirSync(join(paths.home, "bin"), { recursive: true });
  await downloadAndExtract(urls, paths, onNotice);
  return existsSync(paths.bin) ? paths.bin : null;
}

async function downloadAndExtract(
  urls: { tarball: string; checksum: string },
  paths: CollectorPaths,
  onNotice?: (message: string) => void,
): Promise<void> {
  const response = await fetch(urls.tarball, { signal: AbortSignal.timeout(300_000) });
  if (!response.ok || !response.body) {
    throw new Error(`collector download failed: HTTP ${response.status}`);
  }
  const tarball = join(paths.home, "otelcol-contrib.tar.gz");
  await pipeline(response.body, createWriteStream(tarball));

  // Verify against the published checksum; a mismatch means a corrupted or
  // tampered download — discard rather than execute.
  const actual = createHash("sha256").update(readFileSync(tarball)).digest("hex");
  let expected: string | null = null;
  try {
    const checksumResponse = await fetch(urls.checksum, { signal: AbortSignal.timeout(30_000) });
    if (checksumResponse.ok) {
      expected = (await checksumResponse.text()).trim().split(/\s+/)[0] ?? null;
    }
  } catch {
    // fall through to unverified — logged below
  }
  if (!expected) {
    onNotice?.("Warning: collector checksum could not be fetched — download NOT verified");
  }
  if (expected && expected !== actual) {
    rmSync(tarball, { force: true });
    throw new Error(
      `collector checksum mismatch: expected ${expected}, got ${actual} — download discarded`,
    );
  }

  const extracted = spawnSync("tar", ["-xzf", tarball, "-C", join(paths.home, "bin")], {
    stdio: "pipe",
  });
  rmSync(tarball, { force: true });
  if (extracted.status !== 0) {
    throw new Error(
      `collector extraction failed: ${extracted.stderr?.toString().trim() || "tar error"}`,
    );
  }
}

export interface StartCollectorOptions {
  backendUrl: string;
  /** Full Authorization header value, e.g. "Bearer apo_...". Env-only. */
  authHeader: string;
  /** Progress notices (one-time download, startup) — user-facing. */
  onNotice?: (message: string) => void;
}

export interface CollectorHandle {
  /** Loopback base URL the task trace endpoint should point at. */
  traceEndpoint: string;
  /** True when an already-running collector was reused instead of started. */
  reused: boolean;
  /** Graceful stop (SIGTERM, bounded). Queued spans persist on disk. */
  stop(): Promise<void>;
}

/**
 * Start (or reuse) the local collector and wait until it is healthy.
 *
 * Throws on any failure — callers treat that as "fall back to direct export",
 * which is never worse than the pre-collector behavior.
 */
export async function startCollector(opts: StartCollectorOptions): Promise<CollectorHandle> {
  const paths = collectorPaths();
  const otlpPort = intEnv("APO_COLLECTOR_PORT", DEFAULT_OTLP_PORT);
  const healthPort = intEnv("APO_COLLECTOR_HEALTH_PORT", DEFAULT_HEALTH_PORT);

  // A healthy collector on the ports is reused whatever started it: the
  // config is ours (same path impersonation), and a second start would fail
  // to bind anyway. Both ports are probed — a foreign service answering on
  // the health port alone must not trick us into pointing traces at a dead
  // receiver.
  if ((await isHealthy(healthPort)) && (await isReceiverUp(otlpPort))) {
    return {
      traceEndpoint: `http://127.0.0.1:${otlpPort}`,
      reused: true,
      stop: async () => {
        // A reused collector is not ours to stop.
      },
    };
  }

  const bin = await ensureCollectorBinary(opts.onNotice);
  if (!bin) {
    throw new Error("no otelcol-contrib release for this platform");
  }
  if (!existsSync(bin)) {
    // Fail before touching disk — a bad APO_COLLECTOR_BIN or a broken
    // install must not leave half-written state behind.
    throw new Error(`collector binary not found at ${bin}`);
  }

  mkdirSync(paths.queueDir, { recursive: true });
  writeFileSync(
    paths.config,
    renderCollectorConfig({
      backendUrl: opts.backendUrl,
      otlpPort,
      healthPort,
      queueDir: paths.queueDir,
      maxQueueBytes: intEnv("APO_COLLECTOR_MAX_QUEUE_BYTES", DEFAULT_MAX_QUEUE_BYTES),
    }),
  );

  const logFd = openSync(paths.log, "a");
  const child = spawn(bin, ["--config", paths.config], {
    stdio: ["ignore", logFd, logFd],
    env: {
      ...process.env,
      // The one secret the collector needs — argv and config stay clean.
      APO_COLLECTOR_AUTH: opts.authHeader,
    },
  });
  // The child holds its own duplicate of the log fd; the parent's copy can go.
  closeSync(logFd);
  child.unref();

  // Fail fast when the collector dies during startup (bad config, bad
  // binary) instead of waiting out the whole health timeout.
  const earlyExit = new Promise<never>((_, reject) => {
    child.once("exit", (code) => {
      reject(new Error(`collector exited during startup (code ${code}; log: ${paths.log})`));
    });
  });

  try {
    await Promise.race([
      waitForHealth(healthPort, intEnv("APO_COLLECTOR_HEALTH_TIMEOUT_MS", DEFAULT_HEALTH_TIMEOUT_MS)),
      earlyExit,
    ]);
  } catch (error) {
    // Never leave a half-started process behind.
    killCollector(child);
    throw error;
  }
  // A later exit (our own stop, a crash) must not turn this settled promise
  // into an unhandled rejection.
  earlyExit.catch(() => undefined);

  return {
    traceEndpoint: `http://127.0.0.1:${otlpPort}`,
    reused: false,
    stop: () => stopCollector(child),
  };
}

async function isHealthy(healthPort: number): Promise<boolean> {
  try {
    const response = await fetch(`http://127.0.0.1:${healthPort}/`, {
      signal: AbortSignal.timeout(1_000),
    });
    return response.ok;
  } catch {
    return false;
  }
}

/**
 * Whether an OTLP/HTTP receiver answers on apo's traces path. Any HTTP
 * status counts (an empty probe body is a 400); only a dead port does not.
 */
async function isReceiverUp(otlpPort: number): Promise<boolean> {
  try {
    await fetch(`http://127.0.0.1:${otlpPort}${APO_TRACES_PATH}`, {
      method: "POST",
      signal: AbortSignal.timeout(1_000),
    });
    return true;
  } catch {
    return false;
  }
}

async function waitForHealth(healthPort: number, timeoutMs: number): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (await isHealthy(healthPort)) return;
    await new Promise((resolve) => setTimeout(resolve, 250));
  }
  throw new Error(
    `collector not healthy after ${timeoutMs}ms (log: ${collectorPaths().log})`,
  );
}

function stopCollector(child: ChildProcess): Promise<void> {
  return new Promise((resolve) => {
    if (child.exitCode !== null) return resolve();
    const timer = setTimeout(() => {
      killCollector(child);
      resolve();
    }, STOP_TIMEOUT_MS);
    child.once("exit", () => {
      clearTimeout(timer);
      resolve();
    });
    try {
      child.kill("SIGTERM");
    } catch {
      clearTimeout(timer);
      resolve();
    }
  });
}

function killCollector(child: ChildProcess): void {
  try {
    child.kill("SIGKILL");
  } catch {
    // already gone
  }
}

function intEnv(name: string, fallback: number): number {
  const raw = process.env[name];
  if (!raw) return fallback;
  const parsed = Number.parseInt(raw, 10);
  return Number.isSafeInteger(parsed) && parsed > 0 ? parsed : fallback;
}

// ── command-facing facade ─────────────────────────────────────────────────

export interface MaybeCollector {
  /**
   * Loopback base URL task traces should be pointed at, or null when the
   * collector is off/unavailable — callers then use their backend URL
   * directly, exactly the pre-collector behavior.
   */
  traceEndpoint: string | null;
  /** Graceful stop; safe to call unconditionally. */
  stop(): Promise<void>;
}

/**
 * Start the collector when it should run for this backend, with the command's
 * logging. Never throws: any failure degrades to direct export with a
 * warning, which is never worse than not having a collector at all.
 */
export async function maybeStartCollector(input: {
  backendUrl: string;
  /** Full Authorization header value; without one the collector cannot forward. */
  authHeader: string | null;
  log?: (line: string) => void;
  warn?: (line: string) => void;
}): Promise<MaybeCollector> {
  const off: MaybeCollector = { traceEndpoint: null, stop: async () => undefined };
  if (!decideCollectorEnabled(input.backendUrl)) return off;
  if (!input.authHeader) {
    input.warn?.("span buffering off: no stored credential to forward — exporting directly");
    return off;
  }
  try {
    const handle = await startCollector({
      backendUrl: input.backendUrl,
      authHeader: input.authHeader,
      onNotice: (message) => input.log?.(message),
    });
    input.log?.(
      handle.reused
        ? "Span buffering on — reusing the running local collector"
        : "Span buffering on — traces survive network drops and backend outages",
    );
    return handle;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    input.warn?.(`span buffering unavailable (${message}) — exporting traces directly`);
    return off;
  }
}
