"""
apo models - database and schema definitions.

This module re-exports all database models and API schemas for convenient importing.
"""

# Re-export schemas (API request/response models)
# noqa: F401 - These are intentional re-exports
# pyright: reportDuplicateImport=false, reportUnusedImport=false

from ..models.schemas import (  # noqa: F401
    AgentTaskBatchRunDetail,
    AgentTaskBatchRunExternalDetail,
    AgentTaskBatchRunSummary,
    AgentTaskBatchRunConfigurationSummary,
    AgentTaskDetail,
    AgentTaskDeliverableManifest,
    AgentTaskRunConfiguration,
    AgentTaskRunConfigurationCount,
    AgentTaskRunDetail,
    AgentTaskRunExternalSummary,
    AgentTaskRunStats,
    AgentTaskRunSummary,
    AgentTaskRunTrigger,
    FailureBreakdownItem,
    GenerationExecutionSummary,
    AgentTaskSummary,
    ApiKeyCreate,
    ApiKeyCreateResponse,
    ApiKeyResponse,
    ArtifactUploadIntent,
    BatchIngestionRequest,
    BulkScoreRequest,
    BulkScoreResponse,
    CorrectionRequest,
    CreateAgentTaskBatchRunRequest,
    CreateArtifactUploadRequest,
    CreateRunRequest,
    CreateScoreRequest,
    DeliverableSummary,
    FacetBucket,
    IngestionError,
    IngestionEvent,
    IngestionResponse,
    LoggedCall,
    LoggedCallBase,
    ReportAgentTaskRunResultRequest,
    Run,
    RunDetail,
    RunMetric,
    RunSummary,
    RunFacets,
    PaginatedSessionSummary,
    ScoreResponse,
    SessionSummary,
    TruncatedCheckValue,
    UpdateAgentTaskScheduleRequest,
    UpdateRunRequest,
    # Agent task schedule schemas
    AgentTaskScheduleSummary,
    AgentTaskScheduleDetail,
    ScheduleLastBatchSummary,
    CreateAgentTaskScheduleRequest,
    AdaptiveTaskStateSummary,
    ScheduleExecutionOwnerSummary,
    ScheduleOccurrenceSummary,
    TriggerScheduleResponse,
)

# Re-export database models
# noqa: F401 - These are intentional re-exports
from ..models.db import (  # noqa: F401
    AdaptiveTaskStateDB,
    AgentTaskBatchRunDB,
    AgentTaskCheckReportDB,
    AgentTaskDeliverableDB,
    AgentTaskJudgmentDB,
    AgentTaskRunDB,
    AgentTaskScheduleDB,
    ApiKeyDB,
    ArchivedModelDB,
    CallMetricDB,
    LoggedCallDB,
    RunDB,
    RunMetricDB,
    ScoreConfigDB,
    SessionDB,
)

__all__ = [
    # Schemas
    "AgentTaskBatchRunDetail",
    "AgentTaskBatchRunExternalDetail",
    "AgentTaskBatchRunSummary",
    "AgentTaskBatchRunConfigurationSummary",
    "AgentTaskDetail",
    "AgentTaskDeliverableManifest",
    "AgentTaskRunConfiguration",
    "AgentTaskRunConfigurationCount",
    "AgentTaskRunDetail",
    "AgentTaskRunExternalSummary",
    "AgentTaskRunStats",
    "AgentTaskRunSummary",
    "AgentTaskRunTrigger",
    "AgentTaskSummary",
    "ApiKeyCreate",
    "ApiKeyCreateResponse",
    "ApiKeyResponse",
    "ArtifactUploadIntent",
    "BatchIngestionRequest",
    "BulkScoreRequest",
    "BulkScoreResponse",
    "CorrectionRequest",
    "CreateAgentTaskBatchRunRequest",
    "CreateArtifactUploadRequest",
    "CreateRunRequest",
    "CreateScoreRequest",
    "DeliverableSummary",
    "FailureBreakdownItem",
    "GenerationExecutionSummary",
    "FacetBucket",
    "IngestionError",
    "IngestionEvent",
    "IngestionResponse",
    "LoggedCall",
    "LoggedCallBase",
    "ReportAgentTaskRunResultRequest",
    "Run",
    "RunDetail",
    "RunMetric",
    "RunSummary",
    "RunFacets",
    "PaginatedSessionSummary",
    "ScoreResponse",
    "SessionSummary",
    "TruncatedCheckValue",
    "ScheduleLastBatchSummary",
    "UpdateRunRequest",
    # Agent task schedule schemas
    "AgentTaskScheduleSummary",
    "AgentTaskScheduleDetail",
    "CreateAgentTaskScheduleRequest",
    "ScheduleExecutionOwnerSummary",
    "ScheduleOccurrenceSummary",
    "TriggerScheduleResponse",
    "UpdateAgentTaskScheduleRequest",
    "AdaptiveTaskStateSummary",
    # Database models
    "AdaptiveTaskStateDB",
    "AgentTaskBatchRunDB",
    "AgentTaskCheckReportDB",
    "AgentTaskDeliverableDB",
    "AgentTaskJudgmentDB",
    "AgentTaskRunDB",
    "AgentTaskScheduleDB",
    "ApiKeyDB",
    "ArchivedModelDB",
    "CallMetricDB",
    "LoggedCallDB",
    "RunDB",
    "RunMetricDB",
    "ScoreConfigDB",
    "SessionDB",
]
